/**
 * Edge-compatible and Web Crypto-compatible password hashing using PBKDF2.
 * Native to browser and Cloudflare Workers runtime (zero Node.js dependencies).
 */

const ITERATIONS = 100_000
const KEY_LEN = 32 // 256 bits

export async function hashPassword(password: string): Promise<string> {
  const enc = new TextEncoder()
  const salt = crypto.getRandomValues(new Uint8Array(16))
  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    enc.encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveBits"]
  )

  const derivedBits = await crypto.subtle.deriveBits(
    {
      name: "PBKDF2",
      salt,
      iterations: ITERATIONS,
      hash: "SHA-256",
    },
    keyMaterial,
    KEY_LEN * 8
  )

  const hashArray = Array.from(new Uint8Array(derivedBits))
  const saltHex = Array.from(salt)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
  const hashHex = hashArray.map((b) => b.toString(16).padStart(2, "0")).join("")

  return `pbkdf2$${ITERATIONS}$${saltHex}$${hashHex}`
}

export async function verifyPassword(
  storedHash: string,
  attempt: string
): Promise<boolean> {
  if (!storedHash || !attempt) return false

  // If it's a PBKDF2 hash generated by this module:
  if (storedHash.startsWith("pbkdf2$")) {
    const parts = storedHash.split("$")
    if (parts.length !== 4) return false
    const iterations = parseInt(parts[1], 10)
    const saltHex = parts[2]
    const originalHashHex = parts[3]

    const saltMatch = saltHex.match(/.{1,2}/g)
    if (!saltMatch) return false
    const salt = new Uint8Array(saltMatch.map((byte) => parseInt(byte, 16)))

    const enc = new TextEncoder()
    const keyMaterial = await crypto.subtle.importKey(
      "raw",
      enc.encode(attempt),
      { name: "PBKDF2" },
      false,
      ["deriveBits"]
    )

    const derivedBits = await crypto.subtle.deriveBits(
      {
        name: "PBKDF2",
        salt,
        iterations,
        hash: "SHA-256",
      },
      keyMaterial,
      KEY_LEN * 8
    )

    const hashHex = Array.from(new Uint8Array(derivedBits))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("")

    return hashHex === originalHashHex
  }

  // Fallback for migrated bcrypt hashes ($2a$, $2b$, $2y$)
  // For Cloudflare Workers, Better Auth or dynamic verification handles or prompts upgrade
  return false
}
